[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[package]
name = "igraph"
version = "0.10.16"

[package.build.backend]
name = "pixi-build-cmake"
version = "*"
